SisCom/Controllers/posController.cs
using SisCom.Data.IRepositories;
using SisCom.Helpers;
using SisCom.Models;
using SisCom.Structure.Mappers.Pos;
using SisCom.Structure.ViewModels.Pos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SisCom.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class posController : Controller
    {
        private ComEdbEntities _db;
        private PosMapper _posMapper;
        private IPosRepository _posRepository;
        private IDropdownRepository _dropdownRepository;

        public posController
            (
            ComEdbEntities db,
            PosMapper posMapper,
            IPosRepository posRepository,
            IDropdownRepository dropdownRepository
            )
        {
            _db = db;
            _posMapper = posMapper;
            _posRepository = posRepository;
            _dropdownRepository = dropdownRepository;
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult IndexJson(PaginatorGeneric<pos, PosViewModel> paginator)
        {
            List<pos> resultsModel = _posRepository.GetPos();
            var viewmodel = _posMapper.MapperListModelToViewModel(resultsModel);

            if (paginator.Page == 0)
            {
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = _posRepository.GetAllByPaged(paginator);
                var pageCount = (double)result.TotalRow / result.PageSize;

                result.Results = _posMapper.MapperPaginatorModelToViewModel(result);
                result.PageCount = (int)Math.Ceiling(pageCount);
                result.ResultsModel = null;
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateJson()
        {
            var posViewModel = new PosViewModel();
            var dropdowns = GetDropdowns();

            return Json(new { dropdowns, posViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CreatePosJson(PosViewModel posViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (posViewModel.name == null || posViewModel.idUser == 0)
            {
                return Json(new { formSuccess, msjError });
            }
            try
            {
                posViewModel.isActive = true;
                posViewModel.deletedAt = "12/12/12";

                var posModel = _posMapper.MapperViewModelToModel(posViewModel);
                _posRepository.Insert(posModel);

                var urlRedirect = Url.Action("Index", "Pos");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, posViewModel });
            }
            catch (Exception e)
            {
                return Json(new { state });
            }          
        }
        public ActionResult Edit(int idPos)
        {
            PosViewModel posViewModel = new PosViewModel();
            posViewModel.idPos = idPos;

            return View(posViewModel);
        }
        public ActionResult EditJson(int idPos)
        {
            var pos = _posRepository.FindById(idPos);
            var posViewModel = _posMapper.MapperModelToViewModel(pos);
            var dropdowns = GetDropdowns();

            return Json(new { dropdowns, posViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EditPosJson(PosViewModel posViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (posViewModel.name == null || posViewModel.idUser == 0)
            {
                return Json(new { formSuccess, msjError });
            }
            try
            {
                var posModel = _posMapper.MapperViewModelToModel(posViewModel);
                _posRepository.Update(posModel);

                var urlRedirect = Url.Action("Index", "Pos");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, posViewModel });
            }
            catch (Exception e)
            {
                return Json(new { state });
            }
        }
        public ActionResult Detail(int idPos)
        {
            PosViewModel posViewModel = new PosViewModel();
            posViewModel.idPos = idPos;

            return View(posViewModel);
        }
        public ActionResult Delete(int idPos)
        {
            PosViewModel posViewModel = new PosViewModel();
            posViewModel.idPos = idPos;

            return View(posViewModel);
        }
        [HttpPost]
        public ActionResult DeletePosJson(PosViewModel posViewModel)
        {
            posViewModel.isActive = false;
            posViewModel.deletedAt = DateTime.Now.ToString();
            var posModel = _posMapper.MapperViewModelToModel(posViewModel);
            _posRepository.Update(posModel);
            var urlRedirect = Url.Action("Index", "Pos");
            var Message = "El punto de servicio ha sido actualizado correctamente";

            return Json(new { Message, urlRedirect, posViewModel });
        }
        private object GetDropdowns()
        {
            return new
            {
                User = _dropdownRepository.User(),
            };
        }
    }
}

SisCom/Controllers/userController.cs
using SisCom.Data.IRepositories;
using SisCom.Helpers;
using SisCom.Models;
using SisCom.Structure.Mappers.Users;
using SisCom.Structure.ViewModels.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SisCom.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class userController : Controller
    {
        private ComEdbEntities _db;
        private UsersMapper _usersMapper;
        private IUserRepository _userRepository;
        private IDropdownRepository _dropdownRepository;

        public userController
            (
            ComEdbEntities db,
            UsersMapper usersMapper,
            IUserRepository userRepository,
            IDropdownRepository dropdownRepository
            )
        {
            _db = db;
            _usersMapper = usersMapper;
            _userRepository = userRepository;
            _dropdownRepository = dropdownRepository;
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult IndexJson(PaginatorGeneric<user, UsersViewModel> paginator)
        {
            List<user> resultsModel = _userRepository.GetUsers();
            var viewmodel = _usersMapper.MapperListModelToViewModel(resultsModel);

            if (paginator.Page == 0)
            {
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = _userRepository.GetAllByPaged(paginator);
                var pageCount = (double)result.TotalRow / result.PageSize;

                result.Results = _usersMapper.MapperPaginatorModelToViewModel(result);
                result.PageCount = (int)Math.Ceiling(pageCount);
                result.ResultsModel = null;
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateJson()
        {
            var usersViewModel = new UsersViewModel();
            var dropdowns = GetDropdowns();

            return Json(new { dropdowns, usersViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CreateUserJson(UsersViewModel usersViewModel)
        {          
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (usersViewModel.name == null ||
                usersViewModel.fatherLastName == null ||
                usersViewModel.motherLastName == null ||
                usersViewModel.dni == null ||
                usersViewModel.password == null ||
                usersViewModel.idRole == 0 ||
                usersViewModel.idBranch == 0)
            {
                return Json(new { formSuccess, msjError });
            } 
            else if (usersViewModel.dni.Length < 8 || usersViewModel.dni.Length > 12)
            {
                msjError = "*El DNI/CE no puede ser mayor a 12 o menor a 8 dígitos";

                return Json(new { formSuccess, msjError });
            }
            try
            {
                usersViewModel.isActive = true;
                usersViewModel.deletedAt = "12/12/12";

                var userModel = _usersMapper.MapperViewModelToModel(usersViewModel);
                _userRepository.Insert(userModel);

                var urlRedirect = Url.Action("Index", "User");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, usersViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });
            }
        }
        public ActionResult Edit(int idUser)
        {
            UsersViewModel usersViewModel = new UsersViewModel();
            usersViewModel.idUser = idUser;

            return View(usersViewModel);
        }
        public ActionResult EditJson(int idUser)
        {
            var user = _userRepository.FindById(idUser);
            var usersViewModel = _usersMapper.MapperModelToViewModel(user);
            var dropdowns = GetDropdowns();

            return Json(new { dropdowns, usersViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EditUserJson(UsersViewModel usersViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (usersViewModel.name == null ||
                usersViewModel.fatherLastName == null ||
                usersViewModel.motherLastName == null ||
                usersViewModel.dni == null ||
                usersViewModel.password == null ||
                usersViewModel.idRole == 0 ||
                usersViewModel.idBranch == 0)
            {
                return Json(new { formSuccess, msjError });
            }
            else if (usersViewModel.dni.Length != 8)
            {
                msjError = "*El DNI no puede ser mayor o menor a los 8 caracteres";

                return Json(new { formSuccess, msjError });
            }
            try
            {
                var userModel = _usersMapper.MapperViewModelToModel(usersViewModel);
                _userRepository.Update(userModel);

                var urlRedirect = Url.Action("Index", "User");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, usersViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });
            }
        }
        public ActionResult Detail(int idUser)
        {
            UsersViewModel usersViewModel = new UsersViewModel();
            usersViewModel.idUser = idUser;

            return View(usersViewModel);
        }
        public ActionResult Delete(int idUser)
        {
            UsersViewModel usersViewModel = new UsersViewModel();
            usersViewModel.idUser = idUser;

            return View(usersViewModel);
        }
        [HttpPost]
        public ActionResult DeleteUserJson(UsersViewModel usersViewModel)
        {
            usersViewModel.isActive = false;
            usersViewModel.deletedAt = DateTime.Now.ToString();

            var userModel = _usersMapper.MapperViewModelToModel(usersViewModel);
            _userRepository.Update(userModel);
            var urlRedirect = Url.Action("Index", "User");
            var Message = "El usuario ha sido actualizado correctamente";

            return Json(new { Message, urlRedirect, usersViewModel });
        }
        private object GetDropdowns()
        {
            return new
            {
                Branch = _dropdownRepository.Branch(),
                Role = _dropdownRepository.Role(),
            };
        }

        public ActionResult GetUsersToHomeIndex()
        {
            var users = _usersMapper.MapperListModelToViewModel(_userRepository.GetUsers());
            return Json(new { users }, JsonRequestBehavior.AllowGet);
        }
    }
}

SisCom/Views/Shared/_DidNav.cshtml
    <ul class="navbar-nav bg-primary sidebar sidebar-dark accordion" id="accordionSidebar" style="color: aliceblue;">
       
    </ul>

SisCom/Views/Shared/_DidTopBar.cshtml
@using SisCom.Helpers

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <div>
                <a href="@Url.Action("Index", "Home")">
                    <img class="img-profile rounded-circle" src="~/dist/SCL/imagenes/logos/logoEmpresa.jpg" style="max-height:70px;">
                    <span style="font-size: 15px;"><b>Concesionario R&O S.R.L | Hora: <span style="color:red;"> @DateTime.Now.Hour:@(DateTime.Now.Minute < 10 ? "0" + DateTime.Now.Minute : DateTime.Now.Minute.ToString()) @(DateTime.Now.Hour < 12 ? "am" : "pm")</span></b></span>
                </a>
            </div>
        </div>
    </form>
    <!-- Topbar Navbar -->
    <ul class="nav justify-content-center text-uppercase">
        @if (User.IsInRole("Cajero"))
        {
            <li class="nav-item">
                @if (GetUser.getOpenAttendance(User.Identity.Name) > 0)
                {
                    <a href="@Url.Action("Index", "attendance", new { idAttendance = GetUser.getOpenAttendance(User.Identity.Name) })"><i class="fa fa-box"></i> Cerrar Caja</a>
                }
                else
                {
                    <a href="@Url.Action("Index", "attendance" )"><i class="fa fa-box"></i> Abrir Caja</a>
                }
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Sales" )"><i class="fa fa-cash-register"></i> Ventas</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("FastCreate", "Sales" )"><i class="fa fa-cash-register"></i> Extemporáneas</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Supplies" )"><i class="fa fa-carrot"></i> Insumos</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Products" )"><i class="fa fa-drumstick-bite"></i> Productos</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Customers" )"><i class="fa fa-smile-beam"></i> Clientes</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Sales", "reports")"><i class="fa fa-box"></i> Reportes</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "company" )"><i class="fa fa-bars"></i> Empresas</a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a href="@Url.Action("Index", "Home" )"><i class="fa fa-home"></i> Inicio</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Sales" )"><i class="fa fa-cash-register"></i> Ventas</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("FastCreate", "Sales" )"><i class="fa fa-cash-register"></i> Extemporáneas</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Products" )"><i class="fa fa-drumstick-bite"></i> Productos</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Supplies" )"><i class="fa fa-carrot"></i> Insumos</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "ServiceType" )"><i class="fa fa-utensils"></i> Servicios</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index", "Customers" )"><i class="fa fa-smile-beam"></i> Clientes</a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Sales", "reports")"><i class="fa fa-box"></i> Reportes</a>
            </li>

            <li class="nav-item">
                <a class="dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-users"></i> Administrador
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="@Url.Action("Index", "branch" )"><i class="fa fa-drumstick-bite"></i> Sucursales </a>
                    <a class="dropdown-item" href="@Url.Action("Index", "customers" )"><i class="fa fa-drumstick-bite"></i> Clientes</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "products" )"><i class="fa fa-drumstick-bite"></i> Productos</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "organizations" )"><i class="fa fa-drumstick-bite"></i> Organización</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "pos" )"><i class="fa fa-drumstick-bite"></i> Puntos de servicio</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "serviceType" )"><i class="fa fa-drumstick-bite"></i> Tipos de servicio</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "supplies" )"><i class="fa fa-drumstick-bite"></i> Insumos</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "user" )"><i class="fa fa-drumstick-bite"></i> Usuarios</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "workUnit" )"><i class="fa fa-drumstick-bite"></i> Unidades de trabajo</a>
                    <a class="dropdown-item" href="@Url.Action("RegistroAtenciones", "attendance" )"><i class="fa fa-drumstick-bite"></i> Registro de atenciones</a>
                    <a class="dropdown-item" href="@Url.Action("Index", "company" )"><i class="fa fa-drumstick-bite"></i> Empresas</a>
                </div>
            </li>
        }
    </ul>
    @if (User.IsInRole("Cajero"))
    {
        <ul class="nav justify-content-center text-uppercase">
            @if (GetUser.getOpenAttendance(User.Identity.Name) > 0)
            {
                <h3><span class="badge badge-success">Caja abierta</span></h3>
            }
            else
            {
                <h3><span class="badge badge-danger">Caja cerrada</span></h3>
            }
        </ul>
    }

    <!-- Region Reports Dropdown -->
    <!-- End Region Reports Dropdown -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="img-profile rounded-circle" src="~/dist/SCL/imagenes/dashboard/img-user.png" style="max-height:20px;">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("SignOut", "Home")">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Cerrar sesión
                    </a>
                }
            </div>
        </li>
    </ul>
</nav>
@section Scripts {
    @Scripts.Render("~/dist/js/login/logout.js")"
}
<!-- End of Topbar -->

SisCom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SCL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="@Url.Content("~/dist/css/app.css")">
    <link rel="stylesheet" href="@Url.Content("~/dist/css/preloader/.css")">

    @if (IsSectionDefined("Styles"))
    {
        @RenderSection("Styles", required: false)
    }
</head>
<body>
    <div style="position: relative;">
        <div class="se-pre-con text-center" style="position: absolute; z-index: 1000; width: 100%; height: 100%; background-color: aliceblue; opacity: 0.9;">
            <img src="@Url.Content("~/dist/SCL/imagenes/load.svg")" style="margin-top:15%;">
        </div>
        <input type="hidden" id="baseUrl" value="@Url.Content("~/")" />
        <!-- Navigation -->
        @Html.Partial("_DidNav")
        <!-- Content Wrapper -->
        <div class="container-fluid px-4 body-content">
            @Html.Partial("_DidTopBar")
            <div class="container">
                @RenderBody()
            </div>
            <hr />
        </div>
        <footer class="ml-5 text-center" style="bottom:0;">
            <span class="hint-text"> <b><em>Copyright &copy; @DateTime.Now.Year - Desarrollado por el Team SysCom <br /> Todos los derechos reservados. </em> </b></span>
        </footer>
        @RenderSection("featured", required: false)
        <script src="@Url.Content("~/dist/js/layout.js")"></script>
        @if (IsSectionDefined("Scripts"))
        {
            @RenderSection("Scripts", required: false)
        }
    </div>
</body>
</html>

SisCom/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SCL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="@Url.Content("~/dist/css/app.css")">
    <link rel="stylesheet" href="@Url.Content("~/dist/css/preloader/.css")">

    @if (IsSectionDefined("Styles"))
    {
        @RenderSection("Styles", required: false)
    }
</head>
<body>
    <div style="position: relative;">
        <input type="hidden" id="baseUrl" value="@Url.Content("~/")" />
        <div class="container body-content">
            @RenderBody()
            <hr />
        </div>
        @RenderSection("featured", required: false)
        <script src="@Url.Content("~/dist/js/layout.js")"></script>
        @if (IsSectionDefined("Scripts"))
        {
            @RenderSection("Scripts", required: false)
        }
    </div>
</body>
</html>