SisCom/Models/work_unit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public work_unit()
        {
            this.customer = new HashSet<customer>();
            this.product_work_unit = new HashSet<product_work_unit>();
        }
    
        public int idWorkUnit { get; set; }
        public string name { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_work_unit> product_work_unit { get; set; }
    }
}

SisCom/Controllers/WorkUnitController.cs
using SisCom.Data.IRepositories;
using SisCom.Helpers;
using SisCom.Models;
using SisCom.Structure.Mappers.WorkUnit;
using SisCom.Structure.ViewModels.WorkUnit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SisCom.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class workUnitController : Controller
    {
        private ComEdbEntities _db;
        private WorkUnitMapper _workUnitMapper;
        private IWorkUnitRepository _workUnitRepository;

        public workUnitController
            (
            ComEdbEntities db,
            WorkUnitMapper workUnitMapper,
            IWorkUnitRepository workUnitRepository
            )
        {
            _db = db;
            _workUnitMapper = workUnitMapper;
            _workUnitRepository = workUnitRepository;
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult IndexJson(PaginatorGeneric<work_unit, WorkUnitViewModel> paginator)
        {
            List<work_unit> resultsModel = _workUnitRepository.GetWorkUnit();
            var viewmodel = _workUnitMapper.MapperListModelToViewModel(resultsModel);

            if (paginator.Page == 0)
            {
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = _workUnitRepository.GetAllByPaged(paginator);
                var pageCount = (double)result.TotalRow / result.PageSize;

                result.Results = _workUnitMapper.MapperPaginatorModelToViewModel(result);
                result.PageCount = (int)Math.Ceiling(pageCount);
                result.ResultsModel = null;
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateJson()
        {
            var workUnitViewModel = new WorkUnitViewModel();

            return Json(new { workUnitViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CreateWorkUnitJson(WorkUnitViewModel workUnitViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (workUnitViewModel.name == null)
            {
                return Json(new { formSuccess, msjError });
            }
            try
            {
                workUnitViewModel.isActive = true;
                workUnitViewModel.deletedAt = "12/12/12";

                var workUnitModel = _workUnitMapper.MapperViewModelToModel(workUnitViewModel);
                _workUnitRepository.Insert(workUnitModel);

                var urlRedirect = Url.Action("Index", "WorkUnit");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, workUnitViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });
            }
        }
        public ActionResult Edit(int idWorkUnit)
        {
            WorkUnitViewModel workUnitViewModel = new WorkUnitViewModel();
            workUnitViewModel.idWorkUnit = idWorkUnit;

            return View(workUnitViewModel);
        }
        public ActionResult EditJson(int idWorkUnit)
        {
            var workUnit = _workUnitRepository.FindById(idWorkUnit);
            var workUnitViewModel = _workUnitMapper.MapperModelToViewModel(workUnit);

            return Json(new { workUnitViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EditWorkUnitJson(WorkUnitViewModel workUnitViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (workUnitViewModel.name == null)
            {
                return Json(new { formSuccess, msjError });
            }
            try
            {
                var workUnitModel = _workUnitMapper.MapperViewModelToModel(workUnitViewModel);
                _workUnitRepository.Update(workUnitModel);

                var urlRedirect = Url.Action("Index", "WorkUnit");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, workUnitViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });
            }
        }
        public ActionResult Detail(int idWorkUnit)
        {
            WorkUnitViewModel workUnitViewModel = new WorkUnitViewModel();
            workUnitViewModel.idWorkUnit = idWorkUnit;

            return View(workUnitViewModel);
        }
        public ActionResult Delete(int idWorkUnit)
        {
            WorkUnitViewModel workUnitViewModel = new WorkUnitViewModel();
            workUnitViewModel.idWorkUnit = idWorkUnit;

            return View(workUnitViewModel);
        }
        [HttpPost]
        public ActionResult DeleteWorkUnitJson(WorkUnitViewModel workUnitViewModel)
        {
            workUnitViewModel.isActive = false;

            var workUnitModel = _workUnitMapper.MapperViewModelToModel(workUnitViewModel);
            _workUnitRepository.Update(workUnitModel);
            var urlRedirect = Url.Action("Index", "WorkUnit");
            var Message = "La unidad de trabajo ha sido actualizada correctamente";

            return Json(new { Message, urlRedirect, workUnitViewModel });
        }
    }
}

SisCom/Views/WorkUnit/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<div class="wrapper wrapper-content animated fadeInRight" id="workUnitVue">
    @using (Html.BeginForm("Create", "WorkUnit", FormMethod.Post, new { id = "idWorkUnit", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        <div class="card bg-white">
            <div class="card-header bg-white pb-0">
                <h5 class="card-title pt-1 text-center">Registrar nueva unidad de trabajo</h5>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-12">
                        <label for="PaxCab">Nombre de la unidad de trabajo:</label>
                        <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" />
                    </div>
                </div>
                <b class="text-danger" v-if="msjError != undefined">{{ msjError }}</b>
            </div>
            <br />
            <div class="w-100 text-center mb-4">
                <button type="button" class="btn btn-primary" v-on:click="createWorkUnit">Guardar</button>
                <a href="@Url.Action("Index", "WorkUnit")" class="btn btn-danger">Atrás</a>
            </div>
        </div>
    }
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/workUnit/create.js")"></script>
}

SisCom/Views/WorkUnit/Delete.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="workUnitVue" data-url="@Url.Action("EditJson", "WorkUnit", new { idWorkUnit = Model.idWorkUnit })">
    @Html.Partial("_Detail")
    <br />
    <div class="row justify-content-center">
        <button class="btn btn-sm btn-danger" v-on:click="deleteWorkUnit">Desactivar unidad de trabajo</button>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/workUnit/edit.js")"></script>
}

SisCom/Views/WorkUnit/Detail.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="workUnitVue" data-url="@Url.Action("EditJson", "WorkUnit", new { idWorkUnit = Model.idWorkUnit })">
    @Html.Partial("_Detail")
    <br />
    <div class="row justify-content-center">
        <a href="@Url.Action("Index", "WorkUnit")" class="btn btn-warning">Atrás</a>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/workUnit/edit.js")"></script>
}

SisCom/Views/WorkUnit/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="workUnitVue" data-url="@Url.Action("EditJson", "WorkUnit", new { idWorkUnit = Model.idWorkUnit })">
    <div class="card bg-white">
        <div class="card-header bg-white pb-0">
            <h5 class="card-title pt-1 text-center">Editar unidad de trabajo</h5>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="PaxCab">Nombre de la unidad de trabajo</label>
                    <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Estado:</label>
                    <br />
                    <input v-if="!form.isActive" type="radio" name="State" id="Activo" value="true" v-model="form.isActive">
                    <input v-else type="radio" name="State" id="Activo" value="true" v-model="form.isActive" disabled>
                    <label for="Activo"><span></span>Activo</label>

                    <input v-if="!form.isActive" type="radio" name="State" id="Inactivo" value="false" v-model="form.isActive">
                    <input v-else type="radio" name="State" id="Inactivo" value="false" v-model="form.isActive" disabled>
                    <label for="Inactivo"><span></span>Inactivo</label>
                </div>
            </div>
            <b class="text-danger" v-if="msjError != undefined">{{ msjError }}</b>
        </div>
        <br />
        <div class="w-100 text-center mb-4">
            <button type="button" class="btn btn-primary" v-on:click="editWorkUnit">Guardar</button>
            <a href="@Url.Action("Index", "WorkUnit")" class="btn btn-danger">Atrás</a>
        </div>
    </div>

</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/workUnit/edit.js")"></script>
}

SisCom/Views/WorkUnit/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="workUnitVue">
    <h2>Lista de unidades de trabajo</h2>

    <a class="btn btn-sm btn-success my-4 float-right" href="@Url.Action("Create", "workUnit")"><i class="fas fa-plus"></i> Crear Nuevo</a>

    <div class="text-sm-left col-sm-2">
        <p id="t1" class="card-title float-left pt-1">N° de Registros:</p>
        <select class="custom-select custom-select-sm" v-model="PageSizeList" v-on:change="initTables(paginatorList=1)">
            <option selected value="10">10 Registros</option>
            <option value="20">20 Registros</option>
            <option value="50">50 Registros</option>
            <option value="100">100 Registros</option>
        </select>
    </div>
    <table class="table">
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Estado
            </th>
            <th>
                Opciones
            </th>
        </tr>

        <tr v-for="reg in list.Results">
            <td>
                {{ reg.name }}
            </td>
            <td>
                <p class="badge badge-primary" v-if="reg.isActive">Activo</p>
                <p class="badge badge-danger" v-else>Inactivo</p>
            </td>
            <td>
                <a :href="'@Url.Action("Edit", "WorkUnit")' + '?idWorkUnit='+reg.idWorkUnit" class="btn btn-xs btn-primary btn-circle"><i class="fas fa-pencil-alt" title="Editar Formulario"></i></a>
                <a :href="'@Url.Action("Detail", "WorkUnit")' + '?idWorkUnit='+reg.idWorkUnit" class="btn btn-xs btn-info btn-circle"><i class="fas fa-file-alt" title="Detalle Formulario"></i></a>
                <a :href="'@Url.Action("Delete", "WorkUnit")' + '?idWorkUnit='+reg.idWorkUnit" class="btn btn-xs btn-danger btn-circle"><i class="fas fa-trash" title="Desactivar"></i></a>
            </td>
        </tr>
    </table>
    <nav aria-label="Page navigation example">
        <vue-pagination class="pagination justify-content-end"
                        v-model="paginatorList"
                        :total="list.PageCount == 0 ? 1 : list.PageCount"></vue-pagination>
    </nav>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/workUnit/index.js")"></script>
}

SisCom/Views/WorkUnit/_Detail.cshtml
<div class="card bg-white">
    <div class="card-header bg-white pb-0">
        <h5 class="card-title pt-1 text-center">Unidad de trabajo</h5>
    </div>
    <div class="card-body">
        <div class="form-group row">
            <div class="col-md-12">
                <label for="PaxCab">Nombre de la unidad de trabajo</label>
                <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" disabled/>
            </div>
        </div>
    </div>
</div>