SisCom/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_work_unit = new HashSet<product_work_unit>();
            this.sale_detail = new HashSet<sale_detail>();
        }
    
        public int idProduct { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public double grantedPrice { get; set; }
        public Nullable<int> idServiceType { get; set; }
        public Nullable<int> currentStock { get; set; }
        public Nullable<int> minimunStock { get; set; }
        public string withStock { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> idBranch { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual service_type service_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_work_unit> product_work_unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_detail> sale_detail { get; set; }
    }
}

SisCom/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SisCom.Models;
using SisCom.Structure.ViewModels.Products;
using SisCom.Structure.Mappers.Products;
using SisCom.Data.IRepositories;
using SisCom.Helpers;
using SisCom.Filters;

namespace SisCom.Controllers
{

    [Authorize(Roles = "Administrador, Cajero")]
    public class productsController : Controller
    {
        private ComEdbEntities _db;
        private IProductRepository _productRepository;
        private ProductMapper _productMapper;
        private IDropdownRepository _dropdownRepository;

        public productsController
            (
            ComEdbEntities db,
            IProductRepository productRepository,
            ProductMapper productMapper,
            IDropdownRepository dropdownRepository
            )
        {
            _db = db;
            _productRepository = productRepository;
            _productMapper = productMapper;
            _dropdownRepository = dropdownRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult IndexJson(ProductsFilters filters)
        {
            List<product> resultsModel = _productRepository.GetProducts();
            var viewmodel = _productMapper.MapperListModelToViewModel(resultsModel);

            if (filters.Page == 0)
            {
                var list = filters;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = _productRepository.GetAllByPagedFilters(filters);
                var pageCount = (double)result.TotalRow / result.PageSize;

                result.Results = _productMapper.MapperPaginatorModelToViewModel(result);
                result.PageCount = (int)Math.Ceiling(pageCount);
                result.ResultsModel = null;
                var list = filters;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateJson()
        {
            var productViewModel = new ProductViewModel();
            var dropdowns = GetDropdowns();

            return Json(new { dropdowns, productViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CreateProductJson(ProductViewModel productViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (productViewModel.name == null ||
                productViewModel.withStock == null ||
                productViewModel.idServiceType == null ||
                productViewModel.idBranch == null )
            {
                return Json(new { formSuccess, msjError });
            }
            if (productViewModel.withStock == "1")
            {
                if (productViewModel.currentStock == null || productViewModel.minimunStock == null)
                {
                    msjError = "*Por favor, ingresar el stock de los productos";
                    return Json(new { formSuccess, msjError });
                }
            }
            try
            {
                productViewModel.isActive = true;

                var productModel = _productMapper.MapperViewModelToModel(productViewModel);
                _productRepository.Insert(productModel);

                var urlRedirect = Url.Action("Index", "Products");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, productViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });
            }        
        }
        public ActionResult Edit(int idProduct)
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.idProduct = idProduct;

            return View(productViewModel);
        }
        public ActionResult EditJson(int idProduct)
        {
            var product = _productRepository.FindById(idProduct);
            var productViewModel = _productMapper.MapperModelToViewModel(product);
            var dropdowns = GetDropdowns();

            return Json(new { dropdowns, productViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EditProductJson(ProductViewModel productViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (productViewModel.name == null ||
                productViewModel.withStock == null ||
                productViewModel.idServiceType == null ||
                productViewModel.idBranch == null)
            {
                return Json(new { formSuccess, msjError });
            }
            if (productViewModel.withStock == "1" )
            {
                if (productViewModel.currentStock == null || productViewModel.minimunStock == null)
                {
                    msjError = "*Por favor, ingresar el stock de los productos";
                    return Json(new { formSuccess, msjError });
                }
            }
            try
            {
                var productModel = _productMapper.MapperViewModelToModel(productViewModel);
                _productRepository.Update(productModel);

                var urlRedirect = Url.Action("Index", "Products");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, productViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });
            }

        }
        public ActionResult Details(int idProduct)
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.idProduct = idProduct;

            return View(productViewModel);
        }
        public ActionResult Delete(int idProduct)
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.idProduct = idProduct;

            return View(productViewModel);
        }
        [HttpPost]
        public ActionResult DeleteProductJson(ProductViewModel productViewModel)
        {
            productViewModel.isActive = false;
            var productModel = _productMapper.MapperViewModelToModel(productViewModel);
            _productRepository.Update(productModel);
            var urlRedirect = Url.Action("Index", "Products");
            var Message = "El Producto ha sido desactivado correctamente";

            return Json(new { Message, urlRedirect, productViewModel });
        }
        private object GetDropdowns()
        {
            return new
            {
                ServiceType = _dropdownRepository.ServiceType(),
                Branch = _dropdownRepository.Branch(),
            };
        }
        public ActionResult GetActivesAndInactivesProducts()
        {
            var allProducts = _productRepository.GetProducts();
            var activesProducts = allProducts.Where(product => product.isActive).Count();
            var inactivesProducts = allProducts.Where(product => !product.isActive).Count();
            return Json(new { activesProducts, inactivesProducts }, JsonRequestBehavior.AllowGet);
        }
    }
}

SisCom/Views/products/Create.cshtml
@model SisCom.Models.product

@{
    ViewBag.Title = "Create";
}
<div class="wrapper wrapper-content animated fadeInRight" id="productVue">
    @using (Html.BeginForm("Create", "Customers", FormMethod.Post, new { id = "idCustomer", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
    <div class="card bg-white">
        <div class="card-header bg-white pb-0">
            <h5 class="card-title pt-1 text-center">Registrar nuevo producto</h5>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Nombre:</label>
                    <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Precio (S/. ):</label>
                    <input type="number" id="price" name="price" class="form-control form-control-sm" v-model="form.price" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Precio subvencionado (S/. ):</label>
                    <input type="number" id="grantedPrice" name="grantedPrice" class="form-control form-control-sm" v-model="form.grantedPrice" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">¿Producto con stock?</label>
                    <select id="withStock" class="custom-select custom-select-sm" v-on:change="resetStock(form.withStock)" v-model="form.withStock">
                        <option selected value="0">No</option>
                        <option value="1">Si</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="PaxCab">Stock (Und. ):</label>
                    <input v-if="form.withStock == 1" type="number" id="currentStock" name="currentStock" class="form-control form-control-sm" v-model="form.currentStock" />
                    <input v-else type="number" id="currentStock" name="currentStock" class="form-control form-control-sm" v-model="form.currentStock" disabled/>
                </div>
                <div class="col-md-4">
                    <label for="PaxCab">Stock mínimo (Und. ):</label>
                    <input v-if="form.withStock == 1" type="number" id="minimunStock" name="minimunStock" class="form-control form-control-sm" v-model="form.minimunStock" />
                    <input v-else type="number" id="minimunStock" name="minimunStock" class="form-control form-control-sm" v-model="form.minimunStock" disabled/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Tipo de servicio:</label>
                    <select id="idServiceType" class="custom-select custom-select-sm" v-model="form.idServiceType">
                        <option v-for="(state, index) in dropdowns.ServiceType" :value="state.Value">
                            {{ state.Text }}
                        </option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Sucursal:</label>
                    <br />
                    <select id="idBranch" class="custom-select custom-select-sm" v-model="form.idBranch">
                        <option v-for="(state, index) in dropdowns.Branch" :value="state.Value">
                            {{ state.Text }}
                        </option>
                    </select>
                </div>
            </div>
            <b class="text-danger" v-if="msjError != undefined">{{ msjError }}</b>
        </div>
        <br />
        <div class="w-100 text-center mb-4">
            <button type="button" class="btn btn-primary" v-on:click="createProduct">Guardar</button>
            <a href="@Url.Action("Index", "Products")" class="btn btn-danger">Atrás</a>
        </div>
    </div>

    }
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/product/create.js")"></script>
}

SisCom/Views/products/Delete.cshtml
@{
    ViewBag.Title = "Detail";
}
<div class="wrapper wrapper-content animated fadeInRight" id="productVue" data-url="@Url.Action("EditJson", "Products", new { idProduct = Model.idProduct })">
    @Html.Partial("_Detail")
    <br />
    <div class="row justify-content-center">
        <button class="btn btn-sm btn-danger" v-on:click="deleteProduct">Desactivar producto</button>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/product/edit.js")"></script>
}

SisCom/Views/products/Details.cshtml
@{
    ViewBag.Title = "Detail";
}
<div class="wrapper wrapper-content animated fadeInRight" id="productVue" data-url="@Url.Action("EditJson", "Products", new { idProduct = Model.idProduct })">
    @Html.Partial("_Detail")
    <br />
    <div class="row justify-content-center">
        <a href="@Url.Action("Index", "Products")" class="btn btn-warning">Atrás</a>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/product/edit.js")"></script>
}

SisCom/Views/products/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="productVue" data-url="@Url.Action("EditJson", "Products", new { idProduct = Model.idProduct })">
    <div class="card bg-white">
        <div class="card-header bg-white pb-0">
            <h5 class="card-title pt-1 text-center">Editar producto</h5>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Nombre:</label>
                    <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Precio (S/. ):</label>
                    <input type="number" id="price" name="price" class="form-control form-control-sm" v-model="form.price" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Precio subvencionado (S/. ):</label>
                    <input type="number" id="grantedPrice" name="grantedPrice" class="form-control form-control-sm" v-model="form.grantedPrice" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">¿Producto con stock?</label>
                    <select id="withStock" class="custom-select custom-select-sm" v-on:change="resetStock(form.withStock)" v-model="form.withStock">
                        <option selected value="0">No</option>
                        <option value="1">Si</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="PaxCab">Stock (Und. ):</label>
                    <input v-if="form.withStock == 1" type="number" id="currentStock" name="currentStock" class="form-control form-control-sm" v-model="form.currentStock" />
                    <input v-else type="number" id="currentStock" name="currentStock" class="form-control form-control-sm" v-model="form.currentStock" disabled />
                </div>
                <div class="col-md-4">
                    <label for="PaxCab">Stock mínimo (Und. ):</label>
                    <input v-if="form.withStock == 1" type="number" id="minimunStock" name="minimunStock" class="form-control form-control-sm" v-model="form.minimunStock" />
                    <input v-else type="number" id="minimunStock" name="minimunStock" class="form-control form-control-sm" v-model="form.minimunStock" disabled />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Tipo de servicio:</label>
                    <select id="idServiceType" class="custom-select custom-select-sm" v-model="form.idServiceType">
                        <option v-for="(state, index) in dropdowns.ServiceType" :value="state.Value">
                            {{ state.Text }}
                        </option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Sucursal:</label>
                    <br />
                    <select id="idBranch" class="custom-select custom-select-sm" v-model="form.idBranch">
                        <option v-for="(state, index) in dropdowns.Branch" :value="state.Value">
                            {{ state.Text }}
                        </option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4">
                    <label for="PaxCab">Estado:</label>
                    <br />
                    <input v-if="!form.isActive" type="radio" name="State" id="Activo" value="true" v-model="form.isActive">
                    <input v-else type="radio" name="State" id="Activo" value="true" v-model="form.isActive" disabled>
                    <label for="Activo"><span></span>Activo</label>

                    <input v-if="!form.isActive" type="radio" name="State" id="Inactivo" value="false" v-model="form.isActive">
                    <input v-else type="radio" name="State" id="Inactivo" value="false" v-model="form.isActive" disabled>
                    <label for="Inactivo"><span></span>Inactivo</label>
                </div>
            </div>
            <b class="text-danger" v-if="msjError != undefined">{{ msjError }}</b>
        </div>
        <br />
        <div class="w-100 text-center mb-4">
            <button type="button" class="btn btn-primary" v-on:click="editProduct">Guardar</button>
            <a href="@Url.Action("Index", "Products")" class="btn btn-danger">Atrás</a>
        </div>
    </div>

</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/product/edit.js")"></script>
}

SisCom/Views/products/Index.cshtml
@model IEnumerable<SisCom.Models.product>

@{
    ViewBag.Title = "Index";
}
<div id="productVue">
    <h2>Lista de productos</h2>

    <a class="btn btn-sm btn-success my-4 float-right" href="@Url.Action("Create", "products")"><i class="fas fa-plus"></i> Crear Nuevo</a>
    <div class="container-fluid">
        <div class="row">
            <div class="text-sm-center col-sm-6">
                <input class="form-control form-control-sm" style="border-radius: 5px 5px" v-model="FilterByName" v-on:keyup.enter="initTables(paginatorList=1)" type="text" placeholder="Buscar por nombre" />
            </div>
            <div class="text-sm-center col-sm-6">
                <input class="form-control form-control-sm" style="border-radius: 5px 5px" v-model="FilterByServiceType" v-on:keyup.enter="initTables(paginatorList=1)" type="text" placeholder="Buscar por tipo de servicio" />
            </div>
        </div>
    </div>
    
    <div class="text-sm-left col-sm-2">
        <p id="t1" class="card-title float-left pt-1">N° de Registros:</p>
        <select class="custom-select custom-select-sm" v-model="PageSizeList" v-on:change="initTables(paginatorList=1)">
            <option selected value="10">10 Registros</option>
            <option value="20">20 Registros</option>
            <option value="50">50 Registros</option>
            <option value="100">100 Registros</option>
        </select>
    </div>
    <table class="table">
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Precio
            </th>
            <th>
                Precio otorgado
            </th>
            <th>
                Tipo de servicio
            </th>
            <th>
                ¿Con stock?
            </th>
            <th>
                Stock
            </th>
            <th>
                Stock mínimo
            </th>
            <th>
                Sucursal
            </th>
            <th>
                Estado
            </th>
            <th>
                Opciones
            </th>
        </tr>

        <tr v-for="reg in list.Results">
            <td>
                {{ reg.name }}
            </td>
            <td>
                {{ reg.price }}
            </td>
            <td>
                {{ reg.grantedPrice }}
            </td>
            <td>
                {{ reg.ServiceType.name }}
            </td>
            <td>
                <p v-if="reg.withStock == 1">Si</p>
                <p v-else>No</p>
            </td>
            <td>
                <p style="color:red" v-if="reg.currentStock <= reg.minimunStock">{{ reg.currentStock }}</p>
                <p style="color:blue" v-else>{{ reg.currentStock }}</p>
            </td>
            <td>
                {{ reg.minimunStock }}
            </td>
            <td>
                {{ reg.Branch.name }}
            </td>
            <td>
                <p class="badge badge-primary" v-if="reg.isActive">Activo</p>
                <p class="badge badge-danger" v-else>Inactivo</p>
            </td>
            <td>
                <a :href="'@Url.Action("Edit", "Products")' + '?idProduct='+reg.idProduct" class="btn btn-xs btn-primary btn-circle"><i class="fas fa-pencil-alt" title="Editar Formulario"></i></a>
                <a :href="'@Url.Action("Details", "Products")' + '?idProduct='+reg.idProduct" class="btn btn-xs btn-info btn-circle"><i class="fas fa-file-alt" title="Detalle Formulario"></i></a>
                <a :href="'@Url.Action("Delete", "Products")' + '?idProduct='+reg.idProduct" class="btn btn-xs btn-danger btn-circle"><i class="fas fa-trash" title="Desactivar"></i></a>
            </td>
        </tr>
    </table>
    <nav aria-label="Page navigation example">
        <vue-pagination class="pagination justify-content-end"
                        v-model="paginatorList"
                        :total="list.PageCount == 0 ? 1 : list.PageCount"></vue-pagination>
    </nav>
</div>
    @section Scripts {
        <script src="@Url.Content("~/dist/js/product/index.js")"></script>
    }

SisCom/Views/products/_Detail.cshtml
<div class="card bg-white">
    <div class="card-header bg-white pb-0">
        <h5 class="card-title pt-1 text-center">Producto</h5>
    </div>
    <div class="card-body">
        <div class="form-group row">
            <div class="col-md-4">
                <label for="PaxCab">Nombre:</label>
                <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4">
                <label for="PaxCab">Precio:</label>
                <input id="price" name="price" class="form-control form-control-sm" v-model="form.price" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4">
                <label for="PaxCab">Precio otorgado:</label>
                <input id="grantedPrice" name="grantedPrice" class="form-control form-control-sm" v-model="form.grantedPrice" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4">
                <label for="PaxCab">¿Producto con stock?</label>
                <input id="WorkUnit" name="WorkUnit" class="form-control form-control-sm" v-if="form.withStock == 1" value="Si" disabled />
                <input id="WorkUnit" name="WorkUnit" class="form-control form-control-sm" v-else value="No" disabled />
            </div>
            <div class="col-md-4">
                <label for="PaxCab">Stock:</label>
                <input id="currentStock" name="currentStock" class="form-control form-control-sm" v-model="form.currentStock" disabled />
            </div>
            <div class="col-md-4">
                <label for="PaxCab">Stock mínimo:</label>
                <input id="minimunStock" name="minimunStock" class="form-control form-control-sm" v-model="form.minimunStock" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4">
                <label for="PaxCab">Tipo de servicio:</label>
                <input id="WorkUnit" name="WorkUnit" class="form-control form-control-sm" v-model="form.ServiceType.name" disabled />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4">
                <label for="PaxCab">Sucursal:</label>
                <input id="Branch" name="Branch" class="form-control form-control-sm" v-model="form.Branch.name" disabled />
            </div>
        </div>
    </div>
    <br />
</div>