SisCom/Models/branch.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public branch()
        {
            this.product = new HashSet<product>();
            this.supplies = new HashSet<supplies>();
            this.user = new HashSet<user>();
        }
    
        public int idBranch { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplies> supplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
    }
}

SisCom/Controllers/branchController.cs
using SisCom.Data.IRepositories;
using SisCom.Helpers;
using SisCom.Models;
using SisCom.Structure.Mappers.BrachMapper;
using SisCom.Structure.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SisCom.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class branchController : Controller
    {
        private ComEdbEntities _db;
        private BranchMapper _branchMapper;
        private IBranchRepository _branchRepository;

        public branchController
            (
            ComEdbEntities db,
            BranchMapper branchMapper,
            IBranchRepository branchRepository
            )
        {
            _db = db;
            _branchMapper = branchMapper;
            _branchRepository = branchRepository;
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult IndexJson(PaginatorGeneric<branch, BranchViewModel> paginator)
        {
            List<branch> resultsModel = _branchRepository.GetBranch();
            var viewmodel = _branchMapper.MapperListModelToViewModel(resultsModel);
        
            if (paginator.Page == 0)
            {
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var result = _branchRepository.GetAllByPaged(paginator);
                var pageCount = (double)result.TotalRow / result.PageSize;

                result.Results = _branchMapper.MapperPaginatorModelToViewModel(result);
                result.PageCount = (int)Math.Ceiling(pageCount);
                result.ResultsModel = null;
                var list = paginator;

                return Json(new { list }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateJson()
        {
            var branchViewModel = new BranchViewModel();

            return Json(new { branchViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CreateBranchJson(BranchViewModel branchViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (branchViewModel.name == null)
            {
                return Json(new { formSuccess, msjError });
            }
            try
            {
                branchViewModel.isActive = true;
                branchViewModel.createdAt = DateTime.Now.ToString();
                branchViewModel.deletedAt = "12/12/12";

                var branchModel = _branchMapper.MapperViewModelToModel(branchViewModel);
                _branchRepository.Insert(branchModel);

                var urlRedirect = Url.Action("Index", "Branch");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, branchViewModel });
            }
            catch (Exception)
            {              
                return Json(new { state });
            }
        }
        public ActionResult Edit(int idBranch)
        {
            BranchViewModel branchViewModel = new BranchViewModel();
            branchViewModel.idBranch = idBranch;

            return View(branchViewModel);
        }
        public ActionResult EditJson(int idBranch)
        {
            var branch = _branchRepository.FindById(idBranch);
            var branchViewModel = _branchMapper.MapperModelToViewModel(branch);

            return Json(new { branchViewModel }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult EditBranchJson(BranchViewModel branchViewModel)
        {
            bool state = false;
            bool formSuccess = false;
            var msjError = "*Por favor, llenar todor los campos";

            if (branchViewModel.name == null)
            {
                return Json(new { formSuccess, msjError });
            }
            try
            {
                var branchModel = _branchMapper.MapperViewModelToModel(branchViewModel);
                _branchRepository.Update(branchModel);

                var urlRedirect = Url.Action("Index", "Branch");
                state = true;
                formSuccess = true;

                return Json(new { formSuccess, state, urlRedirect, branchViewModel });
            }
            catch (Exception)
            {
                return Json(new { state });          
            }         
        }
        public ActionResult Detail(int idBranch)
        {
            BranchViewModel branchViewModel = new BranchViewModel();
            branchViewModel.idBranch = idBranch;

            return View(branchViewModel);
        }
        public ActionResult Delete(int idBranch)
        {
            BranchViewModel branchViewModel = new BranchViewModel();
            branchViewModel.idBranch = idBranch;

            return View(branchViewModel);
        }
        [HttpPost]
        public ActionResult DeleteBranchJson(BranchViewModel branchViewModel)
        {
            branchViewModel.isActive = false;
            branchViewModel.deletedAt = DateTime.Now.ToString();

            var branchModel = _branchMapper.MapperViewModelToModel(branchViewModel);
            _branchRepository.Update(branchModel);
            var urlRedirect = Url.Action("Index", "Branch");
            var Message = "La sucursal ha sido actualizada correctamente";

            return Json(new { Message, urlRedirect, branchViewModel });
        }
        public void checkSession()
        {
            if (Session["usuario"] == null)
            {
                Response.Redirect("~/login/login");
            }
        }
    }
}

SisCom/Views/branch/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<div class="wrapper wrapper-content animated fadeInRight" id="branchVue">
    @using (Html.BeginForm("Create", "Branch", FormMethod.Post, new { id = "idBranch", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
    <div class="card bg-white">
        <div class="card-header bg-white pb-0">
            <h5 class="card-title pt-1 text-center">Registrar nueva sucursal</h5>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="PaxCab">Nombre:</label>
                    <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" />
                </div>
            </div>
            <b class="text-danger" v-if="msjError != undefined">{{ msjError }}</b>
        </div>
        <br />
        <div class="w-100 text-center mb-4">
            <button type="button" class="btn btn-primary" v-on:click="createBranch">Guardar</button>
            <a href="@Url.Action("Index", "Branch")" class="btn btn-danger">Atrás</a>
        </div>
    </div>
    }
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/branch/create.js")"></script>
}

SisCom/Views/branch/Delete.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="branchVue" data-url="@Url.Action("EditJson", "Branch", new { idBranch = Model.idBranch })">
    @Html.Partial("_Detail")
    <br />
    <div class="row justify-content-center">
        <button class="btn btn-sm btn-danger" v-on:click="deleteBranch">Desactivar sucursal</button>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/branch/edit.js")"></script>
}

SisCom/Views/branch/Detail.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="branchVue" data-url="@Url.Action("EditJson", "Branch", new { idBranch = Model.idBranch })">
    @Html.Partial("_Detail")
    <br />
    <div class="row justify-content-center">
        <a href="@Url.Action("Index", "Branch")" class="btn btn-warning">Atrás</a>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/branch/edit.js")"></script>
}

SisCom/Views/branch/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="wrapper wrapper-content animated fadeInRight" id="branchVue" data-url="@Url.Action("EditJson", "Branch", new { idBranch = Model.idBranch })">
    <div class="card bg-white">
        <div class="card-header bg-white pb-0">
            <h5 class="card-title pt-1 text-center">Editar sucursal</h5>
        </div>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="PaxCab">Nombre:</label>
                    <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" />
                </div>
                <div class="pt-3 col-md-12">
                    <label for="PaxCab">Estado:</label>
                    <br />
                    <input v-if="!form.isActive" type="radio" name="State" id="Activo" value="true" v-model="form.isActive" >
                    <input v-else type="radio" name="State" id="Activo" value="true" v-model="form.isActive" disabled>
                    <label for="Activo"><span></span>Activo</label>

                    <input v-if="!form.isActive" type="radio" name="State" id="Inactivo" value="false" v-model="form.isActive" >
                    <input v-else type="radio" name="State" id="Inactivo" value="false" v-model="form.isActive" disabled>
                    <label for="Inactivo"><span></span>Inactivo</label>
                </div>
            </div>

            <b class="text-danger" v-if="msjError != undefined">{{ msjError }}</b>
        </div>
        <br />
        <div class="w-100 text-center mb-4">
            <button type="button" class="btn btn-primary" v-on:click="editBranch">Guardar</button>
            <a href="@Url.Action("Index", "Branch")" class="btn btn-danger">Atrás</a>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/branch/edit.js")"></script>
}

SisCom/Views/branch/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="branchVue">
    <h2>Lista de surcursales</h2>

    <a class="btn btn-sm btn-success my-4 float-right" href="@Url.Action("Create", "branch")"><i class="fas fa-plus"></i> Crear Nuevo</a>

    <div class="text-sm-left col-sm-2">
        <p id="t1" class="card-title float-left pt-1">N° de Registros:</p>
        <select class="custom-select custom-select-sm" v-model="PageSizeList" v-on:change="initTables(paginatorList=1)">
            <option selected value="10">10 Registros</option>
            <option value="20">20 Registros</option>
            <option value="50">50 Registros</option>
            <option value="100">100 Registros</option>
        </select>
    </div>
    <table class="table">
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Fecha de creación
            </th>
            <th>
                Estado
            </th>
            <th>
                Opciones
                <p class="badge badge-danger"></p>
            </th>
        </tr>

        <tr v-for="reg in list.Results">
            <td>
                {{ reg.name }}
            </td>
            <td>
                {{ reg.createdAt }}
            </td>
            <td>
                <p class="badge badge-primary" v-if="reg.isActive">Activo</p>
                <p class="badge badge-danger" v-else>Inactivo</p>
            </td>
            <td>
                <a :href="'@Url.Action("Edit", "Branch")' + '?idBranch='+reg.idBranch" class="btn btn-xs btn-primary btn-circle"><i class="fas fa-pencil-alt" title="Editar Formulario"></i></a>
                <a :href="'@Url.Action("Detail", "Branch")' + '?idBranch='+reg.idBranch" class="btn btn-xs btn-info btn-circle"><i class="fas fa-file-alt" title="Detalle Formulario"></i></a>
                <a :href="'@Url.Action("Delete", "Branch")' + '?idBranch='+reg.idBranch" class="btn btn-xs btn-danger btn-circle"><i class="fas fa-trash" title="Desactivar"></i></a>
            </td>
        </tr>
    </table>
    <nav aria-label="Page navigation example">
        <vue-pagination class="pagination justify-content-end"
                        v-model="paginatorList"
                        :total="list.PageCount == 0 ? 1 : list.PageCount"></vue-pagination>
    </nav>
</div>
@section Scripts {
    <script src="@Url.Content("~/dist/js/branch/index.js")"></script>
}

SisCom/Views/branch/_Detail.cshtml
<div class="card bg-white">
    <div class="card-header bg-white pb-0">
        <h5 class="card-title pt-1 text-center">Sucursal</h5>
    </div>
    <div class="card-body">
        <div class="form-group row">
            <div class="col-md-12">
                <label for="PaxCab">Nombre:</label>
                <input id="name" name="name" class="form-control form-control-sm" v-model="form.name" disabled/>
            </div>
        </div>
    </div>
</div>